- name: Create User and Group on AIX
  hosts: all
  gather_facts: False
  
  tasks:
  - name: Encrypt password
    command: perl -e 'print crypt("{{ password }}", "salt")'
    register: enc_password
    
  - name: debugging
    debug:
      var: enc_password.stdout
        
  - name: Update password user "{{ user }}" 
    user: 
      name: "{{ user }}" 
      password: "{{ enc_password.stdout }}"
      update_password: always
